name: testenv
channels:
- defaults
- conda-forge
dependencies:
- python=3.7
- cython=0.28
- h5py=2.8
- numpy=1.11
- pandas=0.23
- pytables=3.4
- xarray=0.10
- ase=3.16
- periodictable=1.5
- vtk=8.1
- diffpy.structure=3.0
- pytest-cov
- pytest-runner
- codecov
- flake8
