name: testenv
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- cython=0.25
- h5py=2.6
- numpy=1.11
- pandas=0.19
- pytables=3.3
- xarray=0.8
- dask=1.1 # required downgrade to support numpy=1.11
- ase=3.14
- periodictable=1.5
- diffpy.structure=3.0
- pytest-cov
- pytest-runner
- codecov
- flake8
