name: testenv
channels:
- defaults
- conda-forge
dependencies:
- python=3.5
- cython=0.24
- h5py=2.6
- numpy=1.10
- pandas=0.18
- pytables=3.2
- xarray=0.7
- ase=3.14
- periodictable=1.4
- vtk=7.0
- diffpy.structure=3.0
- pytest-cov
- pytest-runner
- codecov
- flake8
